Refactor on WebGPT
acheong08/ChatGPT pull request #1042
Opened 2023-03-05 16:14 UTC by Arborym

Applying Black formatting and isort to match the rest of the project. Also optimized/refactored some of the functions, removed redundancies, and added missing typing.

2023-03-05 20:29 UTC, NymdaFromSalad requested changes
Remove _apiSearch, it is a pretty much useless wrapper

2023-03-05 20:29 UTC, NymdaFromSalad commented on src/revChatGPT/WebGPT.py
> +def _apiSearch(query: str, numResults: int, timePeriod: str = "", region: str = ""):
TBH, just better to remove this function entirely, and use ddg directly

2023-03-05 20:31 UTC, NymdaFromSalad commented
All else looks good

2023-03-06 00:06 UTC, acheong08 approved these changes

2023-03-06 00:06 UTC, merged