Adding a GUI code example to the wiki
acheong08/ChatGPT pull request #1129
Opened 2023-03-10 16:31 UTC by fredi-python

**another code example for the wiki**
I hope you like it : )
![image](https://user-images.githubusercontent.com/83492589/224370537-bc99dea3-eef5-4591-ba7c-778639953366.png)

2023-03-10 21:39 UTC, Arborym requested changes
Such a cool example! I'd just format it to Black standards and add some f-strings to make it pretty 😄

2023-03-10 21:39 UTC, Arborym commented on wiki/Code-examples.md
> +    history.insert(tk.INSERT, "User: " + prompt + "\n\nChatGPT: " + response + "\n\n\n")
```suggestion
def respond(event: tk.Event) -> None:
    if event.state == 1:
        return
    prompt = textbox.get("1.0", "end-1c")
    response = ""
    for data in chatbot.ask(prompt):
        response = data["message"]
    textbox.delete("1.0", "end-1c")
    history.insert(tk.INSERT, f"User: {prompt}" + "\n\nChatGPT: " + response + "\n\n\n")
```

2023-03-10 23:22 UTC, fredi-python commented
> Such a cool example! I'd just format it to Black standards and add some f-strings to make it pretty 😄

Thank you!
I totally forgot that, after reformatting the file in pycharm 👍

2023-03-11 02:20 UTC, acheong08 approved these changes

2023-03-11 02:20 UTC, merged