refactor config to work with load and save
acheong08/ChatGPT pull request #1131
Opened 2023-03-10 21:18 UTC by joshuabrink1

- refactor save and load functions to be used for config parsing
- include examples in `!help` command for `!save` and `!load`
- update cli to only require `--api_key` when there is no `--config` flag 
- update Readme to include config flag

2023-03-10 21:27 UTC, Arborym requested changes
Few edits

2023-03-10 21:27 UTC, Arborym commented on src/revChatGPT/V3.py
> +    if config:
```suggestion
    # Initialize chatbot
    if config := args.config or os.environ.get("GPT_CONFIG_PATH"):
```

2023-03-10 21:27 UTC, Arborym commented on src/revChatGPT/V3.py
> +        except:
```suggestion
        except Exception:
```

2023-03-10 21:27 UTC, Arborym commented on src/revChatGPT/utils.py
> +        return {key for key in keys if key in class_keys}
```suggestion
        return {key for key in class_keys if key not in keys[1:]}
    # Check if all passed keys are valid
    if invalid_keys := set(keys) - class_keys:
        raise ValueError(
            f"Invalid keys: {invalid_keys}",
        )
    # Only return specified keys that are in class_keys
    return {key for key in keys if key in class_keys}
```

2023-03-11 02:23 UTC, acheong08 approved these changes

2023-03-11 02:23 UTC, merged