Create devcontainer.json
acheong08/ChatGPT pull request #488
Opened 2023-01-26 21:24 UTC by aaa9191

2023-01-27 11:16 UTC, acheong08 approved these changes
Maybe add a section in the wiki explaining this?

2023-01-27 11:16 UTC, acheong08 requested changes
Will approve after some explanation in wiki

2023-02-07 21:30 UTC, 53jk1 approved these changes

2023-02-20 09:04 UTC, acheong08 approved these changes

2023-02-20 09:04 UTC, merged