exception added
acheong08/ChatGPT pull request #549
Opened 2023-02-04 11:28 UTC by redoyrahman02

2023-02-04 11:32 UTC, acheong08 requested changes
exception is raised automatically by

2023-02-04 11:32 UTC, acheong08 commented on src/revChatGPT/Official.py
> +            print("Failed to create due to ", e )
Unnecessary. Exception is thrown automatically by the OpenAI function

2023-02-04 11:32 UTC, acheong08 commented on src/revChatGPT/Official.py
> +                print("Failed to ask.", e )
This alone would be enough

2023-02-07 21:30 UTC, 53jk1 approved these changes

2023-02-14 10:03 UTC, 4664gdh approved these changes

2023-02-20 09:03 UTC, closed without merging