Asynchronous Code Support
acheong08/ChatGPT pull request #857
Opened 2023-02-22 14:10 UTC by Louxsdon

I have implement async/await support using aiohttp and asyncio

2023-02-22 23:58 UTC, acheong08 requested changes
Make a separate class for Async. The original sync class needs to be maintained as people have already written scripts for it

2023-02-23 10:12 UTC, Louxsdon commented
> Make a separate class for Async. The original sync class needs to be maintained as people have already written scripts for it

Okay good, it make sense.
I will do that

2023-02-24 04:32 UTC, acheong08 requested changes
Should be in V1.py as AsyncChatbot class extending Chatbot

2023-02-24 15:27 UTC, acheong08 approved these changes

2023-02-24 15:27 UTC, merged