Chatbot -> ChatBot
acheong08/ChatGPT pull request #97
Opened 2022-12-06 18:51 UTC by joleeee

Either this or fix the docs, the docs specify `from revChatGPT.revChatGPT import ChatBot`, but it's currently called `Chatbot` (lowercase B)

havent tested this

2022-12-06 18:53 UTC, joleeee commented
Are you on windows? Maybe it's why it works for you

2022-12-06 20:07 UTC, superswan requested changes
You would also need to update the import statement in `__main__.py` and the construction of the class in the main function `chatbot = Chatbot(config)`

have you tested this?

2022-12-07 00:13 UTC, joleeee commented
Would just edit the docs but I can't add a PR since it's not part of the repo :)

2022-12-07 00:17 UTC, acheong08 commented
> Either this or fix the docs, the docs specify `from revChatGPT.revChatGPT import ChatBot`, but it's currently called `Chatbot` (lowercase B)
> 
> havent tested this

Where in the docs does it say this?

2022-12-07 00:18 UTC, acheong08 commented
![image](https://user-images.githubusercontent.com/36258159/206054711-f7c99975-dae3-47ec-a5d0-ff1f47a99202.png)

2022-12-07 01:36 UTC, closed without merging